title: Emily Ostrow
description: Ph.D. Student at the University of Kansas
owner:
  name: Emily Ostrow # or company name
#  url: "http://emilyostrow.com" # your URL
first_published: 2019 # if migrating another site, the year of your first publish
                      # Must be a 4-digit integer year (math is used on it)
#url: "http://example.com" # the base hostname & protocol for this site
#baseurl: "" # the subpath of your site, e.g. /blog
            # Note you'll have to move your robots.txt to the root if you want it used.
            # And list multiple sitemaps if there are other subdirectories you want indexed
            # besides this blog.
lang: en-us # used in HTML lang attributes

baseurl:     ""
url:         "www.emilyostrow.com"
date_format: "%b %-d, %Y"
github_username: emilyostrow
twitter_username: emily_ostrow
linkedin_username: emily_ostrow
orcid: 0000-0002-7506-2842

# on landing page
# - set the greeting only if you want to display the first green section
#greeting:
#  title: _Your greeting_  
#  text: _Your detailed greeting text_
# - displayed at the bottom
#closing-head: _Your closing_
#closing-para: _Your detailed closing_

# on all pages (and the first three you list display with greeting, if included)
social:
  twitter: https://twitter.com/emily_ostrow
  github: https://github.com/emilyostrow
 #email: /contact/ # you can configure and use this contact page or use your email addy
  #flickr:
  instagram: https://www.instagram.com/emily_ostrow/
